import "./globals.css";

import { Nunito_Sans } from "next/font/google";
import TanstackQueryProvider from "@/components/tanstack-query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";

import Header from "@/components/header";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${nunitoSans.variable}  antialiased`}
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryProvider>
            <Header />
            {children}
          </TanstackQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
